name: 'Update Trackers List'

on:
  schedule:
    # Runs every Wednesday at 1:00 PM (13:00) UTC
    - cron: '0 13 * * 3'

  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-trackers-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: 'Checkout Repository'
        shell: bash
        run: |
          git clone ${{ github.repository }}
        

      - name: 'Fetching Lists of BT Trackers'
        shell: bash
        run: |
          cp -v ./scripts/fetching-tracker-lists .
          chmod a+rxw ./fetching-tracker-lists
          eval ./fetching-tracker-lists
          rm ./fetching-tracker-lists

      - name: 'Removing Duplicate URIs'
        shell: bash
        run: |
          cp -v ./scripts/remove-duplicates.ps1 .
          chmod a+rxw ./remove-duplicates.ps1
          eval ./remove-duplicates.ps1
          rm ./remove-duplicates.ps1

      - name: 'Commit changes'
        shell: bash
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add ./ultimate_trackers.txt
          CURRENT_TIME=$(date +'%Y-%m-%d %H:%M:%S')
          git commit -m "Updated \`ultimate_trackers.txt\` at $CURRENT_TIME"

      - name: 'Push changes'
        uses: 'ad-m/github-push-action@v0.8.0'
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
